name: energy-fault
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - pyarrow>=7.0.0
  - jupyter>=1.0.0
  - notebook>=6.4.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - scikit-learn>=0.24.0
  - tqdm>=4.62.0
  - pip>=21.0.0
  - ipykernel>=6.0.0
  - black>=22.0.0  # for code formatting
  - pytest>=6.0.0  # for testing
  - pip:
    - jupyter_contrib_nbextensions>=0.5.1
